# Generated by Django 4.1.6 on 2023-04-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_name', models.CharField(max_length=30)),
                ('start_phone', models.IntegerField()),
                ('start_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField()),
                ('mark1', models.IntegerField(default='5')),
                ('course', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('qualification', models.CharField(default='Qualification', max_length=30)),
                ('parent_name', models.CharField(default='name', max_length=30)),
                ('parent_number', models.IntegerField(default='000')),
                ('parent_occupation', models.CharField(default='occupation', max_length=30)),
            ],
        ),
    ]
