# Generated by Django 4.1.6 on 2023-04-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent_number',
            field=models.IntegerField(default='000', max_length=30),
        ),
    ]
