# Generated by Django 4.1.6 on 2023-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='offerfees',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
